(* Grammar for the Durian programming language *)

PROGRAM
    : COMPSTMT
    ;

T
    : "\n"
    | "\r"
    ;

COMPSTMT
    : STMT {T STMT} [T]
    ;

STMT
    : STMT "if" EXPR
    | STMT "while" EXPR
    | "return" EXPR
    | yield CALL_ARGS
    | EXPR
    | IFSTMT
    | WHILESTMT
    | FORSTMT
    | DEFSTMT
    | SWTHSTMT
    | TRYSTMT
    | IOSTMT
    ;

IFSTMT
    : "if" EXPR DO
        COMPSTMT
      {"elif" EXPR DO
        COMPSTMT}
      ["else" DO
        COMPSTMT]
      END
    ;

WHILESTMT
    : "while" EXPR DO COMPSTMT END
    ;

FORSTMT
    : "for" BLOCK_VAR DO
        COMPSTMT
      END
    | "for" VARIABLE "in" EXPR DO
        COMPSTMT
      END
    ;

DEFSTMT
    : "def" IDENTIFIER OPT_PARAMS RETURNS DO
        COMPSTMT
      END
    ;

SWTHSTMT
    : "match" PARAMS DO
        {":" VARIABLE DO
          COMPSTMT
          [SWTHFN]
        END}
        ["default" DO
          COMPSTMT
        END]
      END
    ;

TRYSTMT
    : "try" DO
        COMPSTMT
      END
      "catch" DO
        COMPSTMT
      END
    ;

IOSTMT
    : "in" PARAMS
    : "out" PARAM
    : "outln" PARAM
    ;

EXPR
    : ARG
    | CALL_ARGS
    | ASSIGN
    ;

SWTHFN
    : "cont"
    ;

CALL
    : FUNCTION
    | COMMAND
    ;

COMMAND
    : OPERATION CALL_ARGS
    : PRIMARY::OPERATION CALL_ARGS
    ;

FUNCTION
    : OPERATION [BASIC_CALL]
    : PRIMARY, "::" ,OPERATION [BASIC_CALL]
    ;

BASIC_CALL
    : "(" [CALL_ARGS] ")"
    ;

OPERATION
    : IDENTIFIER
    ;

OPT_PARAMS
    : [PARAMS]
    ;

PARAMS
    : "(" [CALL_ARGS] ")"
    ;

CALL_ARGS
    : ARGS
    | COMMAND
    ;

ARGS
    : ARG (, ARG) *
    ;

ARG
    : LHS = ARG
    | ARG ARITH_OP ARG
    | ARG BOOL_OP ARG
    | ARG BIT_OP ARG
    | PRIMARY
    | "!", ARG
    ;

PRIMARY
    : "(" COMPSTMT ")"
    | ASSIGN
    | VARIABLE
    | STMT
    | PRIMARY "[" LITERAL "]"
    | FUNCTION
    | "$", FUNCTION
    | return ["(" [CALL_ARGS] ")"]
    ;

LINE_COMMENT
    : "#" IDENTIFIER
    ;

LONG_COMMENT
    : "#!" IDENTIFIER "!#"
    ;

ASSIGN
    : VARIABLE " : " TYPE "=" ARG
    ;

TYPE
    : /[A-Z]/, {/[a-zA-Z]/}
    : "...", TYPE
    ;

BLOCK_VAR
    : "(" VARIABLE ";" ARG ";" FUNCTION ")"
    ;

LHS
    : VARIABLE
    | PRIMARY
    | PRIMARY::IDENTIFIER
    ;

LITERAL
    : NUMERIC
    | STRING
    ;

VARIABLE
    : IDENTIFIER
    | "None"
    | "self"
    ;

RETURNS
    : [":" TYPE]
    ;

DO
    : "{"
    | T "{"
    ;

END
    : "}"
    ;

IDENTIFIER
    : /[a-zA-Z_]/, {/[a-zA-Z0-9_]/}
    ;

NUMERIC
    : /[0-9]+/
    ;

STRING
    : "\"" /[a-zA-Z_]+/ "\""
    ;

ARITH_OP
    : "+"
    | "-"
    | "*"
    | "/"
    | "%"
    | "**"
    ;

BOOL_OP
    : "=="
    | "!="
    | "&&"
    | "||"
    | ">"
    | ">="
    | "<"
    | "<="
    | "gt"
    | "gte"
    | "lt"
    | "lte"
    | "or"
    | "and"
    | "xor"
    | "nand"
    | "! "
    ;

BIT_OP
    : "&"
    | "|"
    | "^"
    ;