statement            ::= if_statement
                       | while_statement
                       | print_statement
                       | scan_statement
                       | function_declaration
                       | return_statement
                       | expr;
if_statement         ::= "if" expr "{" block_statement "}" 
                         { "elseif" expr "{" block_statement "}" } 
                         [ "else" "{" block_statement "}" ];      
while_statement      ::= "while" expr "{" block_statement "}";
print_statement      ::= "print" expr;
scan_statement       ::= "scan" ID;
return_statement     ::= "return" expr;
block_statement      ::= { statement NL };
